### Connexion
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Liste des favoris
GET http://localhost:8000/api/favorite/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDE0MzE1MTIsImV4cCI6MTcwMTQzNTExMiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJDaHJpc3RvcGhlciJ9.LCsKjAK_hev7E6wM163c6ciLqt0T_XoJOTa8fN0mWxl7QQkEOivfwf6gNBZUti8Lx6f0QqEKM4DeHfjbcYwwj8v9vn3GSwyoepCkfGkqT2k5X4p90DZe3SGMpjTpL6vVddLX_5sWOnXAEGGyy6EjCE2-poMoWnRRauidAHRwC6ksLwRaDs4PhH-csMVi80CqK4cX6n3xSmoiFnw-EVui7tkJcJxGKWBREOHgWs2QnD1379C6IHtIqKG5qQ_V3vxr26_Z_UO6ap2HFziW5hI_12pP1cXUkAvRoejdhj2FbPmBzEc4kqi7ciPZ_qQxj1I3kdw6HI4VgyPX12E_vETdiwH2NDmGdwFmhD9134KhiH_VyPacvlxSnY3lkN9D0INxC3-AH8N5Oifk5_WrX--Xb39QmXaTgf6m_WfFsJHrPx4SHhEob-N-GPFRZ3QyF3l8uv1ztisS9s7Lv9xokdx2_WhPzHSuf26ayV05IY8dxWjel4Y_AjleGA3qlSVthWq6RmLi7MTfyUAZf6g-PeQiiXh8h2FAZJwtVkKe5qtVisWNyK0CBU-iB6xJ0MGHlEtBtgeQ7BDSXNgo8TFr8X8_44xOvRWqms0JJkfJG33jTv-zM7q8mMSgFIRk-qZ9qeuvp4ie39rBQ8Vrpouhck_fSBjY0eS9gekmbyz9T3_X00Y

### Suppression d'un favoris
DELETE http://localhost:8000/api/favorite/delete/134
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODYwNDcsImV4cCI6MTY5OTg4OTY0Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.fQtmL86OgQC4RbykasaBehw6iPNOPiwlv2DCn8S2EhkDh2K_wUlOMCK2sKd_MyPlueGEhGIvWrSK1Ym94ioG9LTxh3MCh31zetiVu2_p0PZBHiEhbzTZqMwW7tH_As8aFiIm6lDc9l3a5OvrTZBwvqZbjzg0bHuKL5BSe1VdyInjiz12lELV5Zk7Em2G5ZKURDaRjiGq311ZX3BFD8hFmcxoP029RjESjZV761yOskp486NL3JfOAPcse_cmIQH0rQGhg1e_uvP7wf2asaH3WyxgoKvOdR5qR0slA3O2TB3PNUMDkCiZmlGcW7JuPO7ZUZuKJajhSU2bdQ4Q_fRTfQDY2_VpkkayyYkwdfRlWStIWkD-L38gsNKInIFOwBa1m5BsISJSmmnYHh5Z8QNLEKSEbnLL-hA77__RQpGYlBch9S8jzdBsstl0oNld5LOhrXNo6Zknb8BAupd9yb1UWfzQu2iRg2PjTyKmx2s0EAzulcRS11xvuukzcFFCEXkrCmii1x3rGAomYCVAOZsYGyh_xFe3dXx8bRsAjPw58UbwBjymOIGmV5c5OhursK6w5NfHp1S37zRu-4lfdewaUwwaHHuR1wjERECm4SftslD3fZK_22jRtyzd36yYG3uMFFiFTxYhMOHf_W_8dU0rIx6YpZrAK6wz-yYBOhSKMfo

### Ajout d'un favoris
POST http://localhost:8000/api/favorite/add/16
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDEyNTM4MTAsImV4cCI6MTcwMTI1NzQxMCwicm9sZXMiOlsiUk9MRV9NRU1CRVIiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJTdXBlcm1hbiJ9.fn0eUjDK3HakmwQnGi1RQK_dAt4-oavsV1t4jdyWXpmedxqMlwbxQ8D_ahQpmuyyZPC5OZoCrXnrQMmmY_A8DOawYlbrFBsZml1JvvH-Z2fVGC27NG_q57u9zLbuK3bhrcJES_bkz5HIEVbtUQXhLdBcLrcWM6smtzioZHaJLZnjZbegs77-A84xJMMzYTQFnc4WOPmLdZCnfuoLsr6f_tLCpsWp5Qn2ND5eFoMGYpKpFQYkkCeVREO0gbF98Cpu4ORrgssOjcsi34_XA5lQmwOaKjl6bRRN0VKR46v0fVbc38CBvhakcl1Rn-HVzxzp-RnRinQxcBCBU6yR9lxAOQ